# Generated by Django 5.0.1 on 2024-01-28 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_cart_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='users',
        ),
    ]
